# Generated by Django 5.2.7 on 2025-10-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
